### ISSUE TITLE
Ship armor-roll not working

### ISSUE THREAD

**Issue by kagedansa** [kbender84/token-action-hud-coriolis#1]
If you use the armor roll from the HUD, no dice roll is triggered and the following messages appear in the console:

![image](https://github.com/kbender84/token-action-hud-coriolis/assets/110729103/153f7576-bb9f-43cb-8046-26830c5f9c38)

**Comment by kbender84** [comment]
Ok, this is wired, it looks like Foundry can't find something so it reverts to default (skill) roll, and finds out that Ship does not have needed attributes (and has Null instead).
Are you playing in German? Does the same error happens when you switch to English?

**Comment by kagedansa** [comment]
Unfortunately, the problem also occurs in english. 

![grafik](https://github.com/kbender84/token-action-hud-coriolis/assets/110729103/6aebc8a0-c88a-4fea-abd2-27b2171d33f0)

**Comment by kbender84** [comment]
Ok, I've got it, let me check what did I mess up in last update

**Comment by kbender84** [comment]
Found it, missing value assignment because JS decided to pass the number as string. I have forced Number() conversion and it seems to work. I will check if I can fix the initiative issue and push the update tomorrow.

**Comment by kbender84** [comment]
fixed in release 1.1.4, please test

**Comment by kagedansa** [comment]
Works for me. Thank you!
