### ISSUE TITLE
Broken with Coriolis 3.7.0

### ISSUE THREAD

**Issue by kagedansa** [kbender84/token-action-hud-coriolis#4]
The new version Coriolis 3.7.0  has made significant changes to the dice rolls and item-/talent modifications. This seems to have an impact on this module.
No errors appear in the console, but the HUD is no longer displayed.

EDIT: It works again with a few minor changes, but I only got autofire and armor mods to work. Modifications of items or talents do not yet work via the HUD.

[module.zip](https://github.com/kbender84/token-action-hud-coriolis/files/14893878/module.zip)

Just "quick and dirty" to get the module working again.

**Comment by kbender84** [comment]
Thanks for reporting, let me investigate that.

Because it seems they changed a lot
![obraz](https://github.com/kbender84/token-action-hud-coriolis/assets/66570321/a97c9109-f105-44b9-9fa4-754f7c5d102a)

**Comment by kbender84** [comment]
They may have introduced new roll type, I'll need to read trough the yzecoriolis module first. 
Thanks for the hotfix! I'll push it through!

**Comment by kbender84** [comment]
The "quick and dirty" is not working for me  for some reason... let's see

**Comment by kbender84** [comment]
Ok, 1.3.1 is out, and the item modifiers should work now. please check if it works for you.

**Comment by kagedansa** [comment]
The new version has worked perfectly for me so far. Many thanks for taking care of it so quickly!
